version: "3"

services:
  api:
    build: .
    ports:
     - 8000:8000
    depends_on:
      - database
    enviroment:
      - DATABASE_HOST=mongo-db://database:27017
  database:
    image: mongo
    ports:
      - 27017-27017
    volums:
      - ./bd:/data/db